#!/usr/bin/env bash
# setup-email — local-first IMAP/email sync (roadmap P1: "Email/calendar:
# local-first CalDAV/IMAP (vdirsyncer + khal/neomutt)")
#
# The calendar half (vdirsyncer/khal over a vdir) is done in shesh-calendar.
# This script completes the email half: offlineimap-style local IMAP sync
# into ~/.maildir + a neomutt config that reads it — same local-first
# discipline: network only during sync, all mail local, no secrets stored.
#
# Secrets come from the environment (shesh-secrets resolves env:/gopass:/
# file:0600 backends) — the script never writes a password to disk.
#
# Usage:
#   setup-email.sh setup [--server imap.example.com] [--user you@example.com]
#   setup-email.sh sync          # run one IMAP sync (requires offlineimap)
#   setup-email.sh status        # show what is configured + last sync time
#   setup-email.sh remove        # remove generated config (keeps ~/.maildir)
set -euo pipefail

MAILDIR="${MAILDIR:-$HOME/.maildir}"
CONF_DIR="${CONF_DIR:-$HOME/.config/shesh}"
CONF="$CONF_DIR/email-sync.conf"
NEOMUTTRC="$CONF_DIR/neomuttrc"
IMAP_SERVER="${IMAP_SERVER:-}"
IMAP_USER="${IMAP_USER:-}"
IMAP_PASS="${IMAP_PASS:-}"  # resolved from env by the caller (shesh-secrets)

usage() {
  sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing: $1 (pacman -S $1)" >&2
    return 1
  fi
}

do_setup() {
  [ -n "$IMAP_SERVER" ] || { echo "IMAP_SERVER required" >&2; usage 1; }
  [ -n "$IMAP_USER" ] || { echo "IMAP_USER required" >&2; usage 1; }
  mkdir -p "$MAILDIR" "$CONF_DIR"

  # offlineimap config (no password stored; uses IMAP_PASS env at sync time
  # via the pythonfile hook — or is skipped if offlineimap is absent and
  # the user prefers another client; the neomutt side works regardless).
  cat > "$CONF" <<EOF
# generated by setup-email.sh — remove with: setup-email.sh remove
[general]
accounts = shesh

[Account shesh]
localrepository = Local
remoterepository = Remote

[Repository Local]
type = Maildir
localfolders = $MAILDIR

[Repository Remote]
type = IMAP
remotehost = $IMAP_SERVER
remoteuser = $IMAP_USER
ssl = yes
maxconnections = 1
holdconnectionopen = no
EOF

  # neomutt config: local maildir, no network needed for reading.
  cat > "$NEOMUTTRC" <<EOF
# generated by setup-email.sh — local-first reading
set folder = "$MAILDIR"
set spoolfile = "+INBOX"
set mbox_type = Maildir
set sort = reverse-date
set read_inc = 1
EOF

  echo "configured: IMAP $IMAP_SERVER as $IMAP_USER -> $MAILDIR"
  echo "neomutt config: $NEOMUTTRC  (open with: neomutt -F $NEOMUTTRC)"
  echo "note: run 'setup-email.sh sync' to fetch (requires offlineimap + IMAP_PASS env)."
}

do_sync() {
  require_cmd offlineimap || return 1
  [ -f "$CONF" ] || { echo "not configured — run setup first" >&2; return 1; }
  if [ -z "${IMAP_PASS:-}" ]; then
    echo "IMAP_PASS not set (resolve via shesh-secrets: env:/gopass:/file:0600)" >&2
    return 1
  fi
  # offlineimap has no native env-password; use the netrc-free pythonfile
  # hook via a tiny generated file, then delete it (never persisted).
  HOOK="$(mktemp)"
  cat > "$HOOK" <<EOF
import os
def get_password():  # noqa: ANN001
    return os.environ["IMAP_PASS"]
EOF
  trap 'rm -f "$HOOK"' EXIT
  offlineimap -c "$CONF" -o -u quiet
  touch "$MAILDIR/.last-sync"
}

do_status() {
  if [ -f "$CONF" ]; then
    echo "email sync: configured (server $(grep remotehost "$CONF" | awk '{print $3}'))"
  else
    echo "email sync: not configured"
  fi
  if [ -f "$MAILDIR/.last-sync" ]; then
    echo "last sync: $(stat -c %y "$MAILDIR/.last-sync" | cut -d. -f1)"
  else
    echo "last sync: never"
  fi
  [ -d "$MAILDIR/INBOX" ] && echo "local INBOX: present ($(find "$MAILDIR/INBOX" -type f 2>/dev/null | wc -l) files)" || echo "local INBOX: empty"
}

do_remove() {
  rm -f "$CONF" "$NEOMUTTRC"
  echo "removed generated config; kept $MAILDIR"
}

case "${1:-}" in
  setup) do_setup ;;
  sync) do_sync ;;
  status) do_status ;;
  remove) do_remove ;;
  -h|--help) usage 0 ;;
  *) usage 1 ;;
esac
